Readme.md
I want a review before I link to my own blog.
=> Added note about blackfire agent installation

.travis.yml, Readme.md, layers/pgsql/Dockerfile
* Add support for pgsql extension (not pdo-pgsql)
* Build confirmed with Travis CI. https://travis-ci.org/sabmeua/extra-php-extensions
=> Add support for pgsql

Readme.md, docs/create_your_own_extension_layer.md
=> Add docs for create new extension layer #14

.github/workflows/deploy-docker.yml, Makefile
This will fix #9. 
The docker images names will be `bref/extra-pcov-php-74`. 
They are published on each push to master (as "latest) and also on tags. 
@mnapoli I need help to add some secrets.
=> Publish docker images

.github/workflows/deploy-docker.yml, .travis.yml, CHANGELOG.md, Readme.md
=> Prepare release 0.3.0

docs/create_your_own_extension_layer.md
Hello,
This PR will fix : 
- 1 typo in `docs/create_your_own_extension_layer.md`
Cheers! :robot:
=> Fix typo in docs/create_your_own_extension_layer.md

.travis.yml, Readme.md, layers/grpc/Dockerfile
=> Add grpc extension

CHANGELOG.md
It took 1h 10m to build and publish the new layers.
=> Added support for gRPC

.travis.yml, Readme.md, layers/yaml/Dockerfile
=> added yaml support

.travis.yml, Readme.md, layers/uuid/Dockerfile
add [UUID](https://pecl.php.net/package/uuid) extension.
=> Add UUID extension

layers/mongodb/Dockerfile, layers/redis/Dockerfile
as they've moved out from base layers in https://github.com/brefphp/bref/pull/723
=> chore(exts): add redis and mongodb

composer.json, src/Application.php, src/Aws/LayerProvider.php, src/Aws/LayerPublisher.php, src/Command/PublishCommand.php
Let's use AsyncAws instead. 
This is a step towards automated releases.
=> Dont use AWS CLI for publishing

.github/workflows/blackfire.yml, .github/workflows/release.yml, Readme.md, src/Application.php, src/Aws/LayerProvider.php, src/Command/HelpCommand.php
This will fix the "list layers" bug
=> Download layers in paralell

.github/workflows/blackfire.yml
Let's wait merging this PR until we've seen if the cron works
=> Only check blackfire once per day

.github/workflows/blackfire.yml, src/Aws/LayerProvider.php, src/Aws/LayerPublisher.php
We need to slow down our number of request.... We are too fast =)
=> Reduce the number of simultaneous requests

.github/workflows/blackfire.yml, Makefile
(and make sure blackfire is running)
=> Small cleanup

.travis.yml, Readme.md, layers/mongodb/Dockerfile, layers/redis/Dockerfile
=> Adding Redis

.travis.yml, Readme.md, layers/scrypt/Dockerfile
This branch adds [Scrypt-PHP](https://github.com/DomBlack/php-scrypt).
=> Add Scrypt Module

.travis.yml, Readme.md, layers/gd/Dockerfile
Supersedes #37 
Example of tested code snippet:
```php
<?php
$jpg_image = imagecreatefromjpeg('sunset.jpeg');
$white = imagecolorallocate($jpg_image, 255, 255, 255);
$font_path = 'Bely Display.ttf';
$text = "This is a sunset!";
imagettftext($jpg_image, 25, 0, 75, 300, $white, $font_path, $text);
imagejpeg($jpg_image, './sunset_with_legend.jpeg');
imagedestroy($jpg_image);
```
Seems to work as expected :tada:
=> Add GD extension (with freetype support)

.travis.yml, Readme.md, layers/ldap/Dockerfile
Already used it in our own application. Worked great.
=> Add ldap extension

.github/workflows/blackfire.yml
This will fix the build failure.
=> Make sure we do a case insensitive search

CHANGELOG.md, composer.json, layers/amqp/Dockerfile, layers/blackfire/Dockerfile, layers/gmp/Dockerfile, layers/memcached/Dockerfile, layers/odbc-snowflake/Dockerfile, layers/sqlsrv/Dockerfile, layers/yaml/Dockerfile
Related to https://github.com/brefphp/bref/pull/702
=> Build extensions with non-zts

composer.json, src/Application.php, src/Aws/LayerProvider.php, src/Aws/LayerPublisher.php
I will wait for new releases of Symfony and AsyncAws core to merge this
=> Dont sleep, rather retry requests

composer.json, src/Application.php, src/Aws/LayerPublisher.php
Follow up from #98. The last release was really quick and no errors, let's try to increase this a little. 
------
If the CI config is properly set up, then we will not test they layers on this PR.
=> Increase the number of parallel uploads

Makefile
=> "Make test" support for *

layers/imagick/Dockerfile, layers/imagick/test.php
Added test for png, jpeg, gif and webp support.
This will fix #104
=> Update Imagemagick to version 7 & fix png and jpeg support

.github/workflows/ci.yml, .github/workflows/deploy-docker.yml, .github/workflows/release.yml, Makefile
=> Rename CI job & add Docker cache

CHANGELOG.md
This super small PR will see if our "docker layer cache" in PR #119 works.
=> Trigger CI

layers/sqlsrv/Dockerfile, layers/sqlsrv/test.php
=> Fixed SQL Server Library issues

composer.json
Symfony 5.2 and async-aws/core 1.7 are releaased!
=> Stable dependencies

layers/amqp/Dockerfile, layers/blackfire/Dockerfile, layers/cassandra/Dockerfile, layers/ds/Dockerfile, layers/gmp/Dockerfile, layers/grpc/Dockerfile, layers/igbinary/Dockerfile, layers/ldap/Dockerfile, layers/mailparse/Dockerfile, layers/memcached/Dockerfile, layers/mongodb/Dockerfile, layers/odbc-snowflake/Dockerfile, layers/pcov/Dockerfile, layers/pgsql/Dockerfile, layers/redis/Dockerfile, layers/uuid/Dockerfile, layers/xdebug/Dockerfile
=> Updated comment

Readme.md
=> Added "Microsoft" to the readme for SQLSRV

src/Command/PublishCommand.php
This is just for the output when publishing layers
=> Sort layers to make printing a bit more nice

.github/workflows/ci.yml, .github/workflows/deploy-docker.yml, Makefile, layers/amqp/Dockerfile, layers/blackfire/Dockerfile, layers/cassandra/Dockerfile, layers/ds/Dockerfile, layers/gd/Dockerfile, layers/gmp/Dockerfile, layers/grpc/Dockerfile, layers/igbinary/Dockerfile, layers/imagick/Dockerfile, layers/imap/Dockerfile, layers/ldap/Dockerfile, layers/mailparse/Dockerfile, layers/memcache/Dockerfile, layers/memcached/Dockerfile, layers/mongodb/Dockerfile, layers/msgpack/Dockerfile, layers/odbc-snowflake/Dockerfile, layers/pcov/Dockerfile, layers/pgsql/Dockerfile, layers/redis/Dockerfile, layers/scrypt/Dockerfile, layers/sqlsrv/Dockerfile, layers/uuid/Dockerfile, layers/xdebug/Dockerfile, layers/yaml/Dockerfile, tests/Dockerfile
This is related to https://github.com/brefphp/bref/pull/830
Maybe @shouze could help me understand why there is a build failure?
=> Bump to bref/build-php-XX:1.1.4

composer.json
Im not sure this is technically needed. But it does not hurt.
=> Conflict with lower bref versions

layers/amqp/Dockerfile, layers/blackfire/Dockerfile, layers/calendar/Dockerfile, layers/cassandra/Dockerfile, layers/ds/Dockerfile, layers/gd/Dockerfile, layers/gmp/Dockerfile, layers/grpc/Dockerfile, layers/igbinary/Dockerfile, layers/imagick/Dockerfile, layers/imap/Dockerfile, layers/ldap/Dockerfile, layers/mailparse/Dockerfile, layers/memcache/Dockerfile, layers/memcached/Dockerfile, layers/mongodb/Dockerfile, layers/msgpack/Dockerfile, layers/newrelic/Dockerfile, layers/oci8/Dockerfile, layers/odbc-snowflake/Dockerfile, layers/pcov/Dockerfile, layers/pgsql/Dockerfile, layers/rdkafka/Dockerfile, layers/scrypt/Dockerfile, layers/spx/Dockerfile, layers/sqlsrv/Dockerfile, layers/tidy/Dockerfile, layers/uuid/Dockerfile, layers/xdebug/Dockerfile, layers/yaml/Dockerfile
Updates the base Bref PHP docker image version to match test cases
=> Updated the base Bref PHP layer versions

layers/imagick/Dockerfile
=> Add lcms2 library for icc profile manipulation

index.js
Based on [commit](https://github.com/brefphp/bref/commit/a627683f69416812dade926792bbd9ef2cc78f66) I updated the index.js file to support the Serveless framework 3. #310
=> Support for Serverless Framework v3

.github/workflows/blackfire.yml, .github/workflows/deploy-docker.yml, .github/workflows/release.yml
=> Dont specify version of shivammathur/setup-php

layers/grpc/Dockerfile
Zipped file went from 58MB to 4MB
=> Make grpc way smaller

layers/newrelic/Dockerfile
Release notes https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-10-5-0-317/
=>  Upgrade NewRelic PHP Agent to v10.5.0.317

Readme.md, src/Service/RegionProvider.php
=> Allow publishing to a single region

layers/imagick/Dockerfile
Patches security vulnerabilities in dependencies and upgrades to a version of the extension with better PHP 8.2 support (though still incomplete).
=> ImageMagick upgrades

layers/datadog/Dockerfile
=> Specify specific version, so upgrades are explicit and not cached

layers/grpc/Dockerfile
=> Upgrade to `grpc` `1.57.0`

Makefile, layers/sqlsrv/Dockerfile, layers/sqlsrv/test.php, tests/Dockerfile
=> Fix sqlsrv

layers/sqlsrv/Dockerfile
Fixes an issue with the latest PHP PDO versions: https://github.com/laravel/framework/issues/47937
=> update PDO sqlsrv to 5.11.1

layers/newrelic/Dockerfile
Replaces #535 as I accidentally deleted my fork
=> Upgrade NewRelic agent to v10.19.0.9

layers/newrelic/Dockerfile
See release notes
https://github.com/newrelic/newrelic-php-agent/releases/tag/v10.20.0.10
https://github.com/newrelic/newrelic-php-agent/releases/tag/v10.21.0.11
=> Upgrade NewRelic Agent to v10.21.0.11

layers/newrelic/Dockerfile
See release notes
https://github.com/newrelic/newrelic-php-agent/releases/tag/v10.22.0.12
=> Upgrade NewRelic Agent to v10.22.0.12

layers/newrelic/Dockerfile
Release notes https://github.com/newrelic/newrelic-php-agent/releases/tag/v11.0.0.13
=> Upgrade NewRelic Agent to v11.0.0.13

layers/newrelic/Dockerfile
See release notes 
https://github.com/newrelic/newrelic-php-agent/releases/tag/v12.0.0.25
=> Upgrade NewRelic Agent to v12.0.0.24
