- layers/gmp/Dockerfile
I needed the gmp extension to be able to verify RS-256 JWT tokens issued by Cognito using the web-token/jwt-signature-algorithm-rsa library.
It is probably easier to add the gmp extension to the default bref layer, but for now I've created this extra extension layer. I hope this is the correct way of doing things. 
I've only been able to test the layer with Docker so far, which worked great. I created a Dockerfile with the following contents:
```
FROM bref/php-74-fpm-dev
COPY --from=bref/layers/gmp-php-74:latest /opt/bref/include/gmp* /opt/bref/include/
COPY --from=bref/layers/gmp-php-74:latest /opt/bref/lib64/*gmp* /opt/bref/lib64/
COPY --from=bref/layers/gmp-php-74:latest /opt/bref-extra/gmp* /opt/bref-extra/
```
I was hoping there was an easier way to copy all changes from the layer …
> Added gmp extension

- Makefile
I propose changes Makefile to be able to make only specified layer.
It will reduce the  time taken build for contributors.
```bash
$ make layer=pgsql
```
I confirmed that  there are no difference in exported zip files whether or not specifying layer.
> Able to make only specified layer

- composer.json
- src/Aws/LayerProvider.php
It is just a dev-package so this has no real effect on the library. 
Async AWS is way lighter than the official SDK. The vendor folder got 19Mb lighter with this change.
> Use async aws

- .travis.yml
- Readme.md
- layers/pcov/Dockerfile
Added pcov to allow for code coverage data to be collected in build environments.
Tested this on AWS Lambda using the bref PHP 7.4 layer, and seems to work as expected.
> Added pcov

- .github/workflows/deploy-docker.yml
We had a small issue. With this PR the $DOCKER_TAG will be empty or hold a tag name
> Fixed environment variable in CI script

- .travis.yml
- Readme.md
- docs/create_your_own_extension_layer.md
- layers/igbinary/Dockerfile
added igbinary as drop in replacement for the standard php serializer.
Tested with bref php 7.3 layer and bref php 7.4 layer on lambda. Works as expected.
> add igbinary

- .travis.yml
- Readme.md
- layers/imagick/Dockerfile
I tested it with php 7.2, 7.3 and 7.4.
What I tested:
- image can be outputted in the webp format
- the method `compositeImageGravity()` exists
> Add imagick with webp support and binding to newer versions of ImageMagick

- Readme.md
- layers/cassandra/Dockerfile
This PR adds the Datastax PHP Cassandra Driver. It's built from source as the driver provided by Datastax is outdated and not supported / working with PHP 7.2+.
> add php cassandra driver layer

- Readme.md
- layers/odbc-snowflake/Dockerfile
I just had the task to connect to a [snowflake](https://www.snowflake.com) database from a php lambda and therefor had to create a layer to add support for it.
The problem I see with generally supporting it here is that... well the odbc extension itself is probably fine but useless without drivers (unless you really want to use mysql though odbc for some reason).
And snowflake is probably a niche and the driver for it is 160mb alone so making this a catch all layer is also not really possible.
So I don't expect this to be merged like it is but maybe someone else has good ideas or needs exactly this.
> odbc snowflake implementation

- .travis.yml
We will still build it because it is a PR.
> Exclude "prepare-release" branch from Travis

- docs/create_your_own_extension_layer.md
- layers/amqp/Dockerfile
- layers/blackfire/Dockerfile
- layers/cassandra/Dockerfile
- layers/ds/Dockerfile
- layers/gmp/Dockerfile
- layers/grpc/Dockerfile
- layers/igbinary/Dockerfile
- layers/imagick/Dockerfile
- layers/mailparse/Dockerfile
- layers/memcached/Dockerfile
- layers/mongodb/Dockerfile
- layers/odbc-snowflake/Dockerfile
- layers/pcov/Dockerfile
- layers/pgsql/Dockerfile
- layers/redis/Dockerfile
- layers/scrypt/Dockerfile
- layers/uuid/Dockerfile
- layers/xdebug/Dockerfile
- layers/yaml/Dockerfile
So, once this one gets merged you can definitely compose extensions more easily.
As extra extensions docker images are built from `lambci/lambda:provided`, they are pretty big for nothing...
And you possibly have to know more in details if the image requires to copy only resulting extension or also other libraries (lib or lib64?).
```Dockerfile
FROM bref/php-74-fpm-dev
COPY --from=bref/extra-redis-php-74 /opt/bref-extra /opt/bref-extra
COPY --from=bref/extra-imagick-php-74 /opt/bref/lib /opt/bref/lib
COPY --from=bref/extra-imagick-php-74 /opt/bref-extra /opt/bref-extra
```
Lightweight extra extension docker image & no more questions.
```Dockerfile
FROM bref/php-74-fpm-dev
COPY --from=bref/extra-redis-php-74 /opt /opt
COPY --from=bref/extra-imagick-php-74 /opt /opt
```
> chore: use scratch as final image

- Makefile
This will fix #80. 
We cannot use `tar` anymore since it is not available in `scratch`.
> Copy output with docker cp

- Makefile
- Readme.md
This is pure DX. This way you can, for example:
```shell
layer=gd php_versions="74 80" make
```
Maybe it worth to be mentioned into README? :thinking:
> chore(build): allow to override some makefile variables

- composer.json
If Bref decides to release 0.6.0, we should make sure one cannot install the next version of bref extensions. 
From this point on, bref extension is only for Bref 1.0-beta1 and above.
> Make sure we conflict with versions before bref 1.0 beta

- Makefile
- Readme.md
This will not make the build run much faster on CI since the only thing we run in parallel is PHP versions. It also hides the output while running... 
So I prefer to make the automation a little bit less complicated by removing this.
> Remove "parallel"

- .gitattributes
- .github/workflows/release.yml
- Readme.md
- bref-extra
- src/Application.php
- src/Command/PublishCommand.php
This will fix #140. 
The idea was that we only should update layers that have changes, ie different checksums. But the checksums are always different. That is why the checksum check should be removed. 
Instead we look at the changed layers since last commit and update only those.
> Remove checksums.json

- docs/newrelic.md
I'm still a little unsure of what  Line 48: `If using a KMS it
will make it easy to globally change across numerous Lambda's the location of
a daemon, the log level or the license key if you need to change where the data
reports.` means. It seems like it's saying "If you're using a KMS and you set up your configuration to use ENVIRONMENT VARIABLES, it will be easier to globally change the location of the daemon, the log level, or the license key (if you need to change where the data reports) across multiple Lambdas.  
I'm not a SME so I'm not 100% sure what it is supposed to say, but it should maybe be clarified.
I work at New Relic - DJ Zevenbergen
> Just fixed some errors and unclear phrasing.

- Readme.md
- docs/create_your_own_extension_layer.md
- index.js
Fixes #218 and https://github.com/brefphp/bref/pull/909
The Serverless Framework introduced a new variable system in its latest version. I upgraded Bref recently (https://github.com/brefphp/bref/pull/909) but we need to fix this here too.
The problem is that (from what I tried) the bref-extra plugin cannot register the same variable namespace as Bref: `${bref:...}`.
In this PR I moved to a separate namespace: `${bref-extra:...}`. This is unfortunately a BC break.
Here is an example:
```diff
functions:
hello:
handler: index.php
layers:
- ${bref:layer.php-74}
-           - ${bref:extra.gd-php-74}
+           - ${bref-extra:gd-php-74}
```
> #218 Fix variable resolution in new Serverless variables system

- layers/redis/Dockerfile
- tests/Dockerfile
After discovering the Redis extension was failing on PHP startup for 8.1 (https://github.com/brefphp/extra-php-extensions/issues/281), I've now tracked down the extension was being compiled against PHP 8.1 **BETA** 3, rather than RC4. Removing the version on the Docker image should help to keep it in sync going forward with the PHP versions of future Bref releases.
> Update Redis Dockerfile to fix wrong version compiled

- composer.json
Looking at https://github.com/brefphp/extra-php-extensions/actions/workflows/blackfire.yml it seems the deploy process broke 3 days ago and the only changes to the deploy process in that time were updates to symfony/http-client from 5.3.8 to 5.3.10
> Temp fix for deployment issues

- Readme.md
Added to readme with version 7.4 to keep it consistent. I wonder if it would be better to change the readme to use "PHP *x*.*y*" and then reference `${bref-extra:rdkafka-php-xy}`?
> Add RdKafka layer to readme

- layers/odbc-snowflake/Dockerfile
- layers/odbc-snowflake/test.php
The odbc-snowflake layer was about 200mb in size.
Most of it was in the libSnowflake.so with 177mb.
I figured that it contains debug flags, that can be stripped.
This reduces the size of that so file to 73 mb.
Still big, but more than 100mb less.
> update odbc snowflake driver and massively reduce layer size

- layers/sqlsrv/Dockerfile
The versions used are very outdated, this way we're using the latest version with every new build.
> Update to latest sqlsrv

- Readme.md
There are many options to use Redis with PHP ([phpredis](https://github.com/phpredis/phpredis), predis, etc.), it's confusing. I looked at the README and it wasn't clear to me whether it was the phpredis extension (required by a framework), so I thought we might as well clarify.
> Clarify that the redis extension is phpredis

- layers/mongodb/Dockerfile
See #428 
Just a harmless change in the file to force the extension to rebuild, hopefully should pass and fix #428.
> Rebuild MongoDB

- Readme.md
To avoid surprises on new major versions that might be incompatible with each other.
> Add explicit versions in the documentation

- layers/amqp/Dockerfile
The most recent build failed, and on further investigation, the extension on pecl only works on PHP 8.0, not 8.1 and 8.2 - we need to build from source.
> Fixed broken amqp extension

- layers/imagick/Dockerfile
* `libwebp` `1.3.0` -> `1.3.1`
* `libde265` `1.0.11` -> `1.0.12`
* `ImageMagick` `7.1.1-11` -> `7.1.1-15`
> Bug and security patches for `imagick` extension

- layers/elastic-apm/Dockerfile
Elastic agent 1.8.1 is quite buggy. I've updated it to 1.8.4.
Also I've added the required src files, in order the make the implementation work. 
See https://www.elastic.co/guide/en/apm/agent/php/current/setup.html#build-from-source
With out this src files, elastic agent error out.
> Update elastic to v1.8.4

- layers/redis/Dockerfile
It is really necessary to hard code the versions, always, otherwise there's no way to trigger new builds.
> Upgrade to redis 6.0.1

- layers/sqlsrv/Dockerfile
Microsoft released the non-beta version of `5.12.0` of SQLSRV on January 31, 2024. https://learn.microsoft.com/en-us/sql/connect/php/release-notes-php-sql-driver?view=sql-server-ver16
SQLSRV 5.12.0 drops support for PHP 8.0. This PR continues to use `5.11.1` for PHP 8.0, and upgrades 8.1, 8.2 and 8.3 to use `5.12.0`. Previously 8.3 was using `5.12.0beta1`
> Use non-beta SQLSRV 5.12.0 for PHP 8.1 and later

- layers/newrelic/Dockerfile
Release notes
https://github.com/newrelic/newrelic-php-agent/releases/tag/v11.1.0.14 
https://github.com/newrelic/newrelic-php-agent/releases/tag/v11.2.0.15 
https://github.com/newrelic/newrelic-php-agent/releases/tag/v11.3.0.16
> Upgrade NewRelic Agent to v11.3.0.16

- layers/tideways/Dockerfile
Note: I assume this works, but I don't know about bref and thus couldn't end-to-end test it. I verified locally that the Docker image still builds and that the result is identical using [diffoci](https://github.com/reproducible-containers/diffoci).
--------------
The provided tooling will do the heavy lifting of choosing the correct `.so` file for a given PHP version, it will automatically support other architectures and downloading and verification is handled by Docker instead of a manual `curl` command.
> Use official `ghcr.io/tideways/php` docker image for Tideways installation

- .github/workflows/blackfire.yml
- .github/workflows/ci.yml
- .github/workflows/deploy-docker.yml
- .github/workflows/force-update-layer-versions.yml
- .github/workflows/release.yml
I recommend setting up Dependabot for GitHub Actions as a follow-up, because this is the only reliable way to keep track of this.
------------
This adds support for a newer node.js version, ensuring forward-compatibility with GitHub Action Runner updates.
> Update to `actions/checkout@v4`

- layers/datadog/Dockerfile
The layer:php-84-fpm currently causes a crash in the Datadog extension due to profiling being enabled by default.
- https://github.com/DataDog/dd-trace-php/releases/tag/1.5.1
Since the Datadog extension in the layer is pretty outdated, this PR updates it to the latest available version to resolve the crash and benefit from the latest improvements.
> Update datadog extension to support php 84
